networks:
  traefik:
    external: true

services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
    volumes:
      - ${USERDIR}/emulatorjs/config:/config
      - ${USERDIR}/emulatorjs/data:/data
      - /mnt/merged/ROMs/NES:/roms/nes
      - /mnt/merged/ROMs/SNES:/roms/snes
      - /mnt/merged/ROMs/DS:/roms/nds
      - /mnt/merged/ROMs/Playstation:/roms/psx
      - /mnt/merged/ROMs/sega32x:/roms/sega32x
      - /mnt/merged/ROMs/genesis:/roms/segaMS
    restart: unless-stopped

    networks:
      - traefik

    labels:
      - "traefik.enable=true"

      # Traefik Router for Port 80
      - "traefik.http.routers.emulatorjs-http.rule=Host(`games.${DOMAIN}`)"
      - "traefik.http.routers.emulatorjs-http.entrypoints=websecure"
      - "traefik.http.routers.emulatorjs-http.service=emulatorjs-http"
      - "traefik.http.services.emulatorjs-http.loadbalancer.server.port=80"
      - "traefik.http.routers.emulatorjs-http.tls=true"
      - "traefik.http.routers.emulatorjs-http.middlewares=global-auth,securityHeaders"

      # Traefik Router for Port 3000
      - "traefik.http.routers.emulatorjs-3000.rule=Host(`games-backroom.${DOMAIN}`)"
      - "traefik.http.routers.emulatorjs-3000.entrypoints=websecure"
      - "traefik.http.routers.emulatorjs-3000.service=emulatorjs-3000"
      - "traefik.http.services.emulatorjs-3000.loadbalancer.server.port=3000"
      - "traefik.http.routers.emulatorjs-3000.tls=true"
      - "traefik.http.routers.emulatorjs-3000.middlewares=global-auth,securityHeaders"

#    ports:
#      - 3000:3000
#      - 80:80
#      - 4001:4001 #optional

